# Generated by Django 3.2.4 on 2021-10-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='items_accepted',
            field=models.TextField(default=''),
        ),
    ]
